name: telead_e_learning
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dots_indicator: ^3.0.0
  sizer: ^2.0.15
  intl: ^0.18.1
  intl_phone_field: ^3.2.0
  pinput: ^2.3.0
  http: ^1.1.0
  grouped_list: ^5.1.2
  chewie: ^1.7.0
  video_player: ^2.7.0
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.4
  google_sign_in: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets: 
    - assets/images/

